[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  gin66/FastAccelStepper@^0.30.15
  https://github.com/micro-ROS/micro_ros_platformio
board_microros_distro = jazzy
board_microros_transport = serial
board_microros_user_meta = gantry_params.meta
